language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'
install: "composer install"
addons:
  srcclr: true
script:
- mkdir -p build/logs
- ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml
after_script: "vendor/bin/php-coveralls -v"

# Linting and Integration tests need to run first to reset the PR build status to pending
stages:
  - 'Linting'
  - 'Integration tests'
  - 'Test'

jobs:
  include:
    - stage: 'Linting'
      language: php
      php: '7.0'
      install: 'composer global require "squizlabs/php_codesniffer=*"'
      script: 'composer lint'
      after_script: skip
      after_success: travis_terminate 0
    - stage: 'Integration tests'
      merge_mode: replace
      env: SDK=php
      cache: false
      language: python
      install:
        - "pip install awscli"
      before_script:
        - "aws s3 cp s3://optimizely-travisci-artifacts/ci/trigger_fullstack-sdk-compat.sh ci/ && chmod u+x ci/trigger_fullstack-sdk-compat.sh"
      script:
        - "ci/trigger_fullstack-sdk-compat.sh"
      after_script: skip
      after_success: travis_terminate 0
